// src/lib/personas.ts
// 500 personajes icónicos — sin duplicados

export const PERSONAS: string[] = [
  'Heisenberg',
  'Saul Goodman',
  'Gus Fring',
  'Jesse Pinkman',
  'Mike Ehrmantraut',
  'Hank Schrader',
  'Tuco Salamanca',
  'Lalo Salamanca',
  'Nacho Varga',
  'Kim Wexler',
  'Omar Little',
  'Stringer Bell',
  'Jimmy McNulty',
  'Bunk Moreland',
  'Avon Barksdale',
  'Marlo Stanfield',
  'Lester Freamon',
  'Prop Joe',
  'Clay Davis',
  'Bubbles',
  'Tony Soprano',
  'Carmela Soprano',
  'Christopher Moltisanti',
  'Paulie Walnuts',
  'Bobby Baccalieri',
  'Janice Soprano',
  'Dr. Melfi',
  'Junior Soprano',
  'Silvio Dante',
  'Big Pussy',
  'Don Draper',
  'Peggy Olson',
  'Roger Sterling',
  'Joan Holloway',
  'Pete Campbell',
  'Betty Draper',
  'Lane Pryce',
  'Bob Benson',
  'Tyrion Lannister',
  'Cersei Lannister',
  'Daenerys Targaryen',
  'Jon Snow',
  'Arya Stark',
  'Sansa Stark',
  'Jaime Lannister',
  'Ned Stark',
  'Joffrey Baratheon',
  'Littlefinger',
  'Varys',
  'The Hound',
  'Oberyn Martell',
  'Stannis Baratheon',
  'Ramsay Bolton',
  'Melisandre',
  'Davos Seaworth',
  'Olenna Tyrell',
  'Brienne of Tarth',
  'Samwell Tarly',
  'Keyser Söze',
  'Tyler Durden',
  'Travis Bickle',
  'Vito Corleone',
  'Michael Corleone',
  'Jules Winnfield',
  'Vincent Vega',
  'Hans Landa',
  'Anton Chigurh',
  'Patrick Bateman',
  'Alex DeLarge',
  'Jack Torrance',
  'Norman Bates',
  'Max Rockatansky',
  'Philip Marlowe',
  'Sam Spade',
  'Jake Gittes',
  'Harry Lime',
  'Frank Booth',
  'Roy Batty',
  'Rick Deckard',
  'Travis',
  'Lt. Columbo',
  'Hannibal Lecter',
  'Clarice Starling',
  'Buffalo Bill',
  'Francis Dolarhyde',
  'John Wick',
  'Jason Bourne',
  'John McClane',
  'Ethan Hunt',
  'James Bond',
  'Jack Bauer',
  'Bryan Mills',
  'Frank Castle',
  'Leon',
  'Vincent',
  'The Jackal',
  'Beatrix Kiddo',
  'O-Ren Ishii',
  'Bill',
  'Elle Driver',
  'Neo',
  'Trinity',
  'Morpheus',
  'Agent Smith',
  'Sarah Connor',
  'John Connor',
  'T-800',
  'Ellen Ripley',
  'HAL 9000',
  'Ash',
  'R2-D2',
  'C-3PO',
  'Luke Skywalker',
  'Darth Vader',
  'Han Solo',
  'Obi-Wan Kenobi',
  'Yoda',
  'Princess Leia',
  'Kylo Ren',
  'Rey',
  'Mando',
  'Grogu',
  'Imperator Furiosa',
  'Nux',
  'Duke Leto',
  'Paul Atreides',
  'Lady Jessica',
  'Gurney Halleck',
  'Dr. Ellie Sattler',
  'Dr. Ian Malcolm',
  'David 8',
  'Walter',
  'Shaw',
  'Interstellar Cooper',
  'Murph',
  'TARS',
  'Dave Bowman',
  'Frank Poole',
  'Rust Cohle',
  'Marty Hart',
  'Frank Underwood',
  'Claire Underwood',
  'Doug Stamper',
  'Nucky Thompson',
  'Al Capone',
  'Chalky White',
  'Margaret Schroeder',
  'Richard Harrow',
  'Ragnar Lothbrok',
  'Lagertha',
  'Bjorn Ironside',
  'Floki',
  'Rollo',
  'Athelstan',
  'Ivar the Boneless',
  'Dexter Morgan',
  'Deb Morgan',
  'Brian Moser',
  'Arthur Mitchell',
  'Ray Donovan',
  'Abby Donovan',
  'Mickey Donovan',
  'Daenerys',
  'Walter White',
  'Sherlock Holmes',
  'John Watson',
  'Mycroft Holmes',
  'Moriarty',
  'Irene Adler',
  'The Dude',
  'Walter Sobchak',
  'Donny',
  'Ron Burgundy',
  'Brick Tamland',
  'Ferris Bueller',
  'Cameron Frye',
  'Sloane Peterson',
  'Napoleon Dynamite',
  'Pedro',
  'Uncle Rico',
  'Ace Ventura',
  'Lloyd Christmas',
  'Harry Dunne',
  'Derek Zoolander',
  'Hansel',
  'Mugatu',
  'Borat',
  'Bruno',
  'Ali G',
  'Michael Scott',
  'Dwight Schrute',
  'Jim Halpert',
  'Pam Beesly',
  'Kevin Malone',
  'Creed Bratton',
  'Tobias Fünke',
  'George Michael Bluth',
  'Lucille Bluth',
  'Buster Bluth',
  'Gob Bluth',
  'Lindsay Bluth',
  'Maeby Fünke',
  'Barry Zuckerkorn',
  'The Joker',
  'Thanos',
  'Magneto',
  'Lex Luthor',
  'Hans Gruber',
  'Nurse Ratched',
  'Amy Dunne',
  'Annie Wilkes',
  'Hannibal',
  'Iago',
  'Nurse Mildred Ratched',
  'Dolores Umbridge',
  'Cersei',
  'Ramsay',
  'Joffrey',
  'Colonel Kurtz',
  'Judge Holden',
  'Randall Flagg',
  'Lisbeth Salander',
  'Katniss Everdeen',
  'Hermione Granger',
  'Marge Gunderson',
  'Holly Golightly',
  'Norma Desmond',
  'Eve Harrington',
  "Scarlett O'Hara",
  'Vivian Ward',
  'Thelma',
  'Louise',
  'Ripley',
  'Dana Scully',
  'Olivia Benson',
  'Carrie Bradshaw',
  'Miranda Priestly',
  'Andy Sachs',
  'Claire Beauchamp',
  'Lady Macbeth',
  'Medea',
  'Antigone',
  'Jay Gatsby',
  'Nick Carraway',
  'Tom Buchanan',
  'Daisy Buchanan',
  'Atticus Finch',
  'Scout Finch',
  'Boo Radley',
  'Holden Caulfield',
  'Raskolnikov',
  'Prince Myshkin',
  'Ivan Karamazov',
  'Alyosha Karamazov',
  'Jean Valjean',
  'Javert',
  'Edmond Dantès',
  'Captain Ahab',
  'Ishmael',
  'Robinson Crusoe',
  'Hercule Poirot',
  'Miss Marple',
  'Winston Smith',
  'Julia',
  "O'Brien",
  'Bernard Marx',
  'Mustapha Mond',
  'John the Savage',
  'Guy Montag',
  'Beatty',
  'Don Quijote',
  'Sancho Panza',
  'Hamlet',
  'Othello',
  'Macbeth',
  'King Lear',
  'Prospero',
  'Shylock',
  'Falstaff',
  'Dale Cooper',
  'Columbo',
  'Poirot',
  'Jessica Fletcher',
  'Jim Rockford',
  'Barney Miller',
  'Vic Mackey',
  'Andy Sipowicz',
  'Sarah Lund',
  'Kurt Wallander',
  'Martin Beck',
  'Harry Bosch',
  'Dave Robicheaux',
  'Easy Rawlins',
  'Matthew Scudder',
  'V.I. Warshawski',
  'Vash the Stampede',
  'Spike Spiegel',
  'Faye Valentine',
  'Motoko Kusanagi',
  'Batou',
  'Ed',
  'Light Yagami',
  'L Lawliet',
  'Near',
  'Guts',
  'Griffith',
  'Gendo Ikari',
  'Shinji Ikari',
  'Rei Ayanami',
  'Asuka Langley',
  'Vash',
  'Alucard',
  'The Man with No Name',
  'Blondie',
  'Tuco',
  'Angel Eyes',
  'Jesse James',
  'Billy the Kid',
  'Wyatt Earp',
  'Doc Holliday',
  'John Wayne',
  'Shane',
  'Will Kane',
  'Josey Wales',
  'Rooster Cogburn',
  'Mattie Ross',
  'Ziggy Stardust',
  'Aladdin Sane',
  'Major Tom',
  'The Thin White Duke',
  'Axl Rose',
  'Slash',
  'Lemmy Kilmister',
  'Kurt Cobain',
  'Eddie Vedder',
  'Thom Yorke',
  'Nick Cave',
  'Tom Waits',
  'Leonard Cohen',
  'Lou Reed',
  'Iggy Pop',
  'Johnny Rotten',
  'Sid Vicious',
  'Joe Strummer',
  'Mick Jagger',
  'Keith Richards',
  'Napoleon',
  'Julius Caesar',
  'Cleopatra',
  'Hannibal Barca',
  'Spartacus',
  'Leonidas',
  'Achilles',
  'Odysseus',
  'Agamemnon',
  'Hector',
  'Ajax',
  'Maximus',
  'Commodus',
  'Gladiator',
  'Braveheart',
  'Rob Roy',
  'El Cid',
  'Bruce Wayne',
  'Tony Stark',
  'Steve Rogers',
  'Natasha Romanoff',
  'Nick Fury',
  'Logan',
  'Wade Wilson',
  'Peter Parker',
  'Matt Murdock',
  'Jessica Jones',
  'Luke Cage',
  'Danny Rand',
  'Clint Barton',
  'Sam Wilson',
  'Bucky Barnes',
  "T'Challa",
  'Stephen Strange',
  'Scott Lang',
  'Carol Danvers',
  'Al Swearengen',
  'Seth Bullock',
  'Sol Star',
  'Calamity Jane',
  'Wild Bill Hickok',
  'E.B. Farnum',
  'Cy Tolliver',
  'Ellsworth',
  'Silas Adams',
  'Bill Compton',
  'Eric Northman',
  'Sookie Stackhouse',
  'Lafayette Reynolds',
  'Pam Swynford',
  'Godric',
  'Russell Edgington',
  'Negan',
  'Rick Grimes',
  'Daryl Dixon',
  'Michonne',
  'The Governor',
  'Carol Peletier',
  'Glenn Rhee',
  'Maggie Greene',
  'Abraham Ford',
  'Beth Greene',
  'Merle Dixon',
  'McMurphy',
  'Chief Bromden',
  'Billy Bibbit',
  'Harry Callahan',
  'Martin Brody',
  'Matt Hooper',
  'Quint',
  'Indiana Jones',
  'Henry Jones Sr.',
  'Short Round',
  'Marion Ravenwood',
  'Rick Blaine',
  'Ilsa Lund',
  'Louis Renault',
  'Major Strasser',
  'Sam',
  'Ugarte',
  'George Bailey',
  'Mr. Potter',
  'Clarence',
  'Forrest Gump',
  'Lt. Dan',
  'Bubba',
  'Jenny',
  'Edward Scissorhands',
  'Willy Wonka',
  'Frank Costello',
  'Billy Costigan',
  'Colin Sullivan',
  'Oliver Wendell Douglas',
  'Verbal Kint',
  'Kaiser Soze',
  'Randall',
  'Dante',
  'Silent Bob',
  'Jay',
  'Banky',
  'Holden McNeil',
  'Alyssa Jones',
  'Brodie Bruce',
  'T.S. Quint',
  'Willam Black',
  'Chasing Amy',
  'Red',
  'Andy Dufresne',
  'Ellis Boyd Redding',
  'Warden Norton',
  'Tommy Williams',
  'Tommy Shelby',
  'Arthur Shelby',
  'Polly Gray',
  'Alfie Solomons',
  'Jimmy McGill',
  'Chuck McGill',
  'Howard Hamlin',
  'Roy Kent',
  'Ted Lasso',
  'Rebecca Welton',
  'Jamie Tartt',
  'Nate Shelley',
  'Keeley Jones',
  'Beard',
  'The Prisoner',
  'Number Six',
  'Harry Haller',
  'Dorian Gray',
  'Basil Hallward',
  'Svidrigailov',
  'Porfiry Petrovich',
  'Hans Castorp',
  'Settembrini',
  'Caleb',
  'Dolores',
  'Maeve',
  'Bernard',
  'The Man in Black',
  'Ford',
  'Jimmy Darmody',
  'Lucky Luciano',
  'Jax Teller',
  'Gemma Teller',
  'Clay Morrow',
  'Chibs Telford',
  'Tig Trager',
  'Opie Winston',
  'Evelyn Mulwray',
  'Noah Cross',
  'Zelig',
  'Virgil Starkwell',
  'Alvy Singer',
  'Isaac Davis',
];

/**
 * Aleatorio — diferente cada vez.
 */
export function getRandomPersona(): string {
  return PERSONAS[Math.floor(Math.random() * PERSONAS.length)];
}

/**
 * Estable por día — el mismo toda la jornada, cambia a medianoche.
 */
export function getDailyPersona(): string {
  const dayOfYear = Math.floor(
    (Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / 86400000
  );
  return PERSONAS[dayOfYear % PERSONAS.length];
}
